<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelangganSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pelanggan')->insert([
            [
                'nama' => 'Siti Rahmawati',
                'telepon' => '081234567890',
                'email' => 'siti.rahmawati@gmail.com',
                'alamat' => 'Jl. Merdeka No. 45, RT 03/RW 02, Kelurahan Kebon Jeruk, Jakarta Barat',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1995-03-12',
                'loyalty_points' => 450,
                'total_pembelian' => 2750000,
                'total_transaksi' => 23,
            ],
            [
                'nama' => 'Bambang Supriyadi',
                'telepon' => '081298765432',
                'email' => 'bambang.supri@gmail.com',
                'alamat' => 'Perumahan Griya Asri Blok C12, Ngaliyan, Semarang',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1988-07-25',
                'loyalty_points' => 320,
                'total_pembelian' => 1850000,
                'total_transaksi' => 15,
            ],
            [
                'nama' => 'Dewi Sartika Putri',
                'telepon' => '087812345678',
                'email' => 'dewi.sartika@yahoo.com',
                'alamat' => 'Jl. Diponegoro No. 88, Surabaya',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2000-11-03',
                'loyalty_points' => 680,
                'total_pembelian' => 4200000,
                'total_transaksi' => 31,
            ],
            [
                'nama' => 'Ahmad Fauzi',
                'telepon' => '085612345678',
                'email' => 'ahmad.fauzi@gmail.com',
                'alamat' => 'Komp. Bumi Indah Permai Blok A5, Bandung',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1992-09-18',
                'loyalty_points' => 210,
                'total_pembelian' => 1350000,
                'total_transaksi' => 10,
            ],
            [
                'nama' => 'Rina Marlina',
                'telepon' => '082134567890',
                'email' => 'rina.marlina@outlook.com',
                'alamat' => 'Jl. Pahlawan No. 21, Yogyakarta',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1997-05-30',
                'loyalty_points' => 890,
                'total_pembelian' => 5100000,
                'total_transaksi' => 42,
            ],
            [
                'nama' => 'Hendra Gunawan',
                'telepon' => '081567890123',
                'email' => 'hendra.gunawan@gmail.com',
                'alamat' => 'Jl. Sudirman No. 156, Medan',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1985-12-08',
                'loyalty_points' => 150,
                'total_pembelian' => 980000,
                'total_transaksi' => 7,
            ],
            [
                'nama' => 'Fitri Handayani',
                'telepon' => '085734567890',
                'email' => 'fitri.handayani@gmail.com',
                'alamat' => 'Perum Puri Permata H5, Sidoarjo',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1993-08-15',
                'loyalty_points' => 560,
                'total_pembelian' => 3200000,
                'total_transaksi' => 28,
            ],
            [
                'nama' => 'Doni Prasetyo',
                'telepon' => '081934567890',
                'email' => 'doni.prasetyo@gmail.com',
                'alamat' => 'Jl. Gatot Subroto Kav. 78, Jakarta Selatan',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1990-01-22',
                'loyalty_points' => 390,
                'total_pembelian' => 2100000,
                'total_transaksi' => 18,
            ],
            [
                'nama' => 'Mega Wulandari',
                'telepon' => '087834567890',
                'email' => 'mega.wulandari@icloud.com',
                'alamat' => 'Jl. Malioboro No. 34, Sleman, DIY',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1998-06-05',
                'loyalty_points' => 720,
                'total_pembelian' => 4600000,
                'total_transaksi' => 35,
            ],
            [
                'nama' => 'Agus Wijaya',
                'telepon' => '081267890123',
                'email' => 'agus.wijaya@gmail.com',
                'alamat' => 'Komp. Citra Garden Blok D8, Malang',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1987-04-14',
                'loyalty_points' => 180,
                'total_pembelian' => 1150000,
                'total_transaksi' => 9,
            ],
            [
                'nama' => 'Nurul Hidayah',
                'telepon' => '085812345678',
                'email' => 'nurul.hidayah@gmail.com',
                'alamat' => 'Jl. Ahmad Yani No. 67, Purwokerto',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2001-10-28',
                'loyalty_points' => 410,
                'total_pembelian' => 2500000,
                'total_transaksi' => 20,
            ],
            [
                'nama' => 'Eko Prasetyo Nugroho',
                'telepon' => '081456789012',
                'email' => 'eko.prasetyo@gmail.com',
                'alamat' => 'Perum Pondok Indah B10, Solo',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1991-02-19',
                'loyalty_points' => 290,
                'total_pembelian' => 1750000,
                'total_transaksi' => 13,
            ],
        ]);
    }
}
